In [8]:
import numpy as np
import string

In [73]:
dt = np.dtype([('col0', float), ('col1', float), ('col2'), 'U1'])
a = np.zeros(3000).reshape(1000, 3)
a

TypeError: Field elements must be 2- or 3-tuples, got ''col2''

In [6]:
a[:,0] = np.random.uniform(0, 100, 1000)
a

array([[52.88414049,  0.        ,  0.        ],
       [56.04922072,  0.        ,  0.        ],
       [43.13217858,  0.        ,  0.        ],
       ...,
       [11.44324158,  0.        ,  0.        ],
       [55.55987414,  0.        ,  0.        ],
       [83.75478845,  0.        ,  0.        ]])

In [7]:
a[:,1] = np.random.randint(0, 100, 1000)
a

array([[52.88414049, 60.        ,  0.        ],
       [56.04922072, 18.        ,  0.        ],
       [43.13217858, 51.        ,  0.        ],
       ...,
       [11.44324158, 59.        ,  0.        ],
       [55.55987414, 37.        ,  0.        ],
       [83.75478845, 66.        ,  0.        ]])

In [71]:
import random

def rand_char(y):
    return [random.choice(string.ascii_letters) for x in range(y)]

alpha = np.array(rand_char(1000))

alpha.shape

(1000,)

In [72]:
a[:,2] = alpha

ValueError: could not convert string to float: 'J'

In [64]:
a.shape

(1000, 3)

In [70]:
a[:,2]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.