In [1]:
import numpy as np

In [2]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
nz

(array([0, 1, 4], dtype=int64),)

In [3]:
print(nz)

(array([0, 1, 4], dtype=int64),)


In [4]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [5]:
np.nonzero(a)

(array([], dtype=int64),)

In [9]:
b = np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
b.reshape(9,)

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [30]:
np.random.randint(100, size = (3))

array([27, 66,  4])

In [20]:
np.random.randint(5, size = (3,4))

array([[3, 4, 2, 2],
       [1, 4, 0, 4],
       [3, 0, 1, 3]])

In [23]:
np.random.random(3)

array([0.44479937, 0.78252717, 0.04687069])

In [26]:
np.random.random((3,3))

array([[0.17668437, 0.99537223, 0.19473494],
       [0.87985876, 0.12992085, 0.50411725],
       [0.1962521 , 0.68497973, 0.76757414]])

In [27]:
np.random.rand(3)

array([0.50870809, 0.97376354, 0.48435212])

In [22]:
np.random.rand(4,5)

array([[0.71987406, 0.9542982 , 0.16490541, 0.2449935 , 0.41601975],
       [0.45387584, 0.73246827, 0.38454162, 0.11097975, 0.68423011],
       [0.31157191, 0.22798731, 0.38436658, 0.98510459, 0.78225377],
       [0.14985949, 0.16944738, 0.93451998, 0.37762398, 0.83621611]])

In [31]:
np.random.rand(3,3,3)

array([[[0.04501756, 0.35190778, 0.26782182],
        [0.86490322, 0.94476202, 0.48806072],
        [0.12621755, 0.39208429, 0.42585148]],

       [[0.45226258, 0.11913923, 0.68050909],
        [0.5320847 , 0.12121427, 0.27488899],
        [0.43673019, 0.075616  , 0.65946111]],

       [[0.75754543, 0.04339303, 0.3567206 ],
        [0.8920902 , 0.14148787, 0.13336229],
        [0.97742777, 0.67123864, 0.67315719]]])

In [32]:
np.random.random((3, 3, 3))

array([[[0.86396863, 0.60008662, 0.98595908],
        [0.01122948, 0.70870498, 0.83039587],
        [0.33796167, 0.13877425, 0.10112198]],

       [[0.05477604, 0.81015279, 0.70493013],
        [0.37288428, 0.67310187, 0.19471775],
        [0.26041283, 0.39823946, 0.36945718]],

       [[0.12219505, 0.04808338, 0.84498598],
        [0.7479103 , 0.40985656, 0.11093746],
        [0.62241021, 0.139236  , 0.6086124 ]]])

In [34]:
np.random.randint(100, size=(3,3,3))

array([[[ 2, 15, 83],
        [50, 19, 90],
        [ 9,  7, 79]],

       [[67, 54, 12],
        [45, 32, 74],
        [96, 59, 14]],

       [[ 8, 37, 72],
        [59,  3, 82],
        [91, 71, 89]]])

In [46]:
c =np.random.randint(100, size=(1,))
c

array([81])

In [47]:
c.max()

81

In [60]:
d = np.random.randint(25, size=(5,5))
d

array([[ 5,  7,  2, 23, 18],
       [ 3, 17, 15,  5, 18],
       [ 1,  1, 22,  3,  5],
       [ 8, 11,  4,  7,  4],
       [23,  8, 18,  9,  2]])

In [61]:
d.max()

23

In [65]:
np.random.randint(25, size=(5,5)).max()

22

In [67]:
np.random.randint(1000, size=(10,10)).max()

982

In [68]:
np.random.randint(1000, size=(10,10)).min()

7

In [69]:
np.random.random(30).mean()

0.5411288373045017

In [82]:
e = np.zeros(9).reshape(3,3)
e

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [85]:
e[:, ::2] = 1
e

array([[1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.]])

In [87]:
e[::2,] = 1
e

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [88]:
f = np.ones(9).reshape(3,3)
f

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [90]:
f[1::2, 1::2] = 0
f

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [96]:
g = np.ones((10,10))
g

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [99]:
g[1:-1, 1:-1] = 0
g

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [101]:
h = np.arange(25).reshape(5,5)
h

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [105]:
i = np.zeros((7, 7))
i

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [106]:
i[1:-1, 1:-1] = h
i

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  2.,  3.,  4.,  0.],
       [ 0.,  5.,  6.,  7.,  8.,  9.,  0.],
       [ 0., 10., 11., 12., 13., 14.,  0.],
       [ 0., 15., 16., 17., 18., 19.,  0.],
       [ 0., 20., 21., 22., 23., 24.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [107]:
0 * np.nan

nan

In [108]:
np.nan == np.nan

False

In [109]:
np.inf > np.nan

False

In [110]:
np.nan - np.nan

nan

In [111]:
np.nan in set([np.nan])

True

In [112]:
0.3 == 3 * 0.1

False

In [121]:
np.diag(np.arange(10), k=0)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [127]:
np.diag(2+np.arange(5), k=2)

array([[0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 6],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [128]:
np.diag(1+np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [129]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [136]:
j = np.zeros((8,8))
j

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [137]:
j[::2,::2] = 1
j

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [138]:
j[1::2, 1::2] = 1
j

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [139]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [142]:
np.tile( np.array([ [0,1],[1,0] ]), (4,4) )

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [146]:
k = np.random.random((5,5))
k

array([[0.06588247, 0.85052845, 0.01057171, 0.39276935, 0.29342776],
       [0.90604202, 0.35406273, 0.61353641, 0.00299846, 0.73510652],
       [0.98031079, 0.85223555, 0.27622719, 0.97195296, 0.47384176],
       [0.87952009, 0.42995851, 0.70906692, 0.74024313, 0.80608952],
       [0.10437427, 0.0862691 , 0.89580579, 0.36760147, 0.69048466]])

In [149]:
(k - np.mean(k)) / np.std(k)

array([[-1.47512319,  0.96843479, -1.6473729 , -0.45712645, -0.76649774],
       [ 1.14131611, -0.57766728,  0.23039012, -1.67095764,  0.60898584],
       [ 1.37260517,  0.97375107, -0.82006405,  1.3465771 , -0.20464935],
       [ 1.05872105, -0.34131133,  0.52789287,  0.62498237,  0.83004233],
       [-1.35525135, -1.4116348 ,  1.10943827, -0.53550469,  0.47002368]])